services:
  - type: web
    name: portfolio
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npx vite preview --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_ENV
        value: production
    pullRequestPreviewsEnabled: true
